export const environment = {
  production: true,
  AUTHORITY_URI: "https://accounts.hgmedia.app",
  CLIENT_ID: "stock_admin",
  API_BASE_URL: "https://stock-api.hgmedia.app",
  LOGIN_REDIRECT_URL: "https://stock-admin.hgmedia.app/authentication/login-callback",
  SCOPE: "openid profile email stock-api offline_access",
  POST_LOGOUT_REDIRECT_URL: "https://stock-admin.hgmedia.app",
  MAX_NOTIFICATION_NUM: 10,
  BASE_URL_USER_PATH: "https://stock.hgmedia.app",
  title: 'HG STOCK',
  NAME_SYSTEM: 'HG Media',
  NAME_RESOURCES: 'HG',
  LOGO_PANDEMIC:'/assets/icons/Logo-HgStock.svg',
  LOGO_ICON: '/assets/images/Logo.svg',
};
